version: 2

models:

    - name: sales
      description: performing several tests in order to check the validity of our data of the set sales
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description: checking that the orders_id are not null
            tests : 
            - not_null 

          - name: products_id
            description: checking that the products_id are not null
            tests:
              - not_null

          - name: qty

          - name: turnover
            description: >
              testing that the turnover is not null
            tests:
              - not_null

          - name: purchase_cost
            description: testing that the purchase costs are not null
            tests:
              - not_null

          - name: margin